# Generated by Django 6.0.3 on 2026-03-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('price', models.DecimalField(decimal_places=2, help_text='В рублях, например 5500000.00', max_digits=12, verbose_name='Цена')),
                ('rooms', models.PositiveSmallIntegerField(verbose_name='Количество комнат')),
                ('area', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Площадь (м²)')),
                ('description', models.TextField(verbose_name='Описание')),
                ('latitude', models.FloatField(blank=True, help_text='Например, 45.03547', null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, help_text='Например, 38.97531', null=True, verbose_name='Долгота')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Главное фото')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать ли объект на сайте', verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Объект недвижимости',
                'verbose_name_plural': 'Объекты недвижимости',
                'ordering': ['-created_at'],
            },
        ),
    ]
