# Generated by Django 6.0.3 on 2026-03-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='calls_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Звонки'),
        ),
        migrations.AddField(
            model_name='property',
            name='views_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Просмотры'),
        ),
    ]
